"""empty message

Revision ID: d4c6cc172865
Revises: 
Create Date: 2024-01-13 18:03:40.517683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c6cc172865'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', 'CRITICAL', name='priority'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('priority',
               existing_type=sa.Enum('VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', 'CRITICAL', name='priority'),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
